# Build and push builder container

name: Container

on:
  push:
    branches: [main]
    paths: [builder/*]
  pull_request:
    branches: [main]
    paths: [builder/*]
  schedule:
    - cron: "40 14 1 * *"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

# Separate PRs can run concurrently; everything else has to queue
concurrency: container-${{ github.event.number }}

env:
  CONTAINER_IMAGE: ghcr.io/${{ github.repository_owner }}/winbuild-builder:latest

jobs:
  container:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: openslide/openslide-winbuild
      - name: Build container
        run: |
          podman build -t $CONTAINER_IMAGE builder
      - name: Push container
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" |
              podman login ghcr.io -u $ --password-stdin
          podman push $CONTAINER_IMAGE
