# Privileged workflow to process issue events

name: Issue event

on:
  issues:
    types: [opened, closed]

permissions:
  issues: write

env:
  GH_LABEL: update

jobs:
  issue-event:
    name: Process
    runs-on: ubuntu-latest
    outputs:
      bot-user: ${{ steps.bot-user.outputs.username }}
    steps:
      - name: Get bot username
        id: bot-user
        env:
          GITHUB_TOKEN: ${{ secrets.OPENSLIDE_BOT_TOKEN }}
        run: echo "username=$(gh api user -q .login)" >> $GITHUB_OUTPUT
      - name: Label dependency issue
        if: >-
          github.event.action == 'opened' &&
          github.actor == steps.bot-user.outputs.username &&
          contains(github.event.issue.body, 'topic=dependencies')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit -R "${{ github.repository }}" \
              "${{ github.event.issue.number }}" \
              --add-label $GH_LABEL
  update-from-issue:
    name: Check for updates
    needs: issue-event
    if: >-
      github.event.action == 'closed' &&
      github.event.issue.user.login == needs.issue-event.outputs.bot-user &&
      contains(github.event.issue.body, 'topic=dependencies')
    uses: ./.github/workflows/update-check.yml
    secrets: inherit
