# Build stable releases on push to openslide-winbuild main.
# Nightly builds from Git are handled elsewhere.

name: Build main

on:
  push:
    # branches: [main]

permissions:
  contents: read

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      pkgver: ${{ steps.params.outputs.pkgver }}
    steps:
      - name: Calculate parameters
        id: params
        run: echo "pkgver=main" >> $GITHUB_OUTPUT

  cross-platform-builds:
    name:
    needs: setup
    uses: ./.github/workflows/build.yml
    with:
      openslide_repo: openslide/openslide
      openslide_ref: main
      openslide_winbuild_repo: ${{ github.repository }}
      openslide_winbuild_ref: ${{ github.ref }}
      pkgver: ${{ needs.setup.outputs.pkgver }}
