# Build stable releases on push to openslide-winbuild main.
# Nightly builds from Git are handled elsewhere.

name: Build main

on:
  push:
    # branches: [main]

permissions:
  contents: read

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      builder_repo_and_digest: ${{ steps.find.outputs.builder_repo_and_digest }}
      pkgver: ${{ steps.params.outputs.pkgver }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Find builder container digest
        id: find
        uses: ./.github/find-container-digest
      - name: Calculate parameters
        id: params
        run: echo "pkgver=main" >> $GITHUB_OUTPUT

  cross-platform-builds:
    name: Cross-platform builds
    needs: setup
    uses: ./.github/workflows/build.yml
    with:
      builder_repo_and_digest: ${{ needs.setup.outputs.builder_repo_and_digest }}
      openslide_ref: main
      openslide_winbuild_repo: ${{ github.repository }}
      openslide_winbuild_ref: ${{ github.ref }}
      pkgver: ${{ needs.setup.outputs.pkgver }}
  jar:
    name: Build JAR
    needs: cross-platform-builds
    uses: ./.github/workflows/jar.yml
