name: Publish release to SciJava Maven

on: 
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with: 
        repo: alanocallaghan/openslide-crossplatform-builds
        workflow: jar.yml
        name: openslide-natives
        name_is_regexp: true
    - name: Publish snapshot
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: publish -P release=true
      env:
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASS: ${{ secrets.MAVEN_PASS }}

